# Banco de palavras para deixar os codigos mais organizados, tire ou adicone palavras aqui.


#palavras com 5 letras
palavras_5 = ['sagaz', 'negro', 'âmago', 'êxito', 'mexer', 'termo', 'senso', 'nobre', 'algoz', 'afeto', 'plena', 'ética', 'mútua', 'sutil', 'tênue', 'vigor', 'aquém', 'audaz', 'porém', 'fazer', 'sanar', 'seção', 'inato', 'assim', 'cerne', 'ideia', 'desde', 'fosse', 'poder', 'moral', 'torpe', 'honra', 'muito', 'justo', 'anexo', 'fútil', 'razão', 'quiçá', 'etnia', 'ícone', 'sobre', 'tange', 'égide', 'lapso', 'mútuo', 'sonho', 'expor', 'haver', 'hábil', 'casal', 'amigo', 'tempo', 'pesar', 'posse', 'ávido', 'então', 'boçal', 'ardil', 'coser', 'genro', 'corja', 'seara', 'dengo', 'prole', 'detém', 'causa', 'dizer', 'tenaz', 'digno', 'porra', 'dever', 'crivo', 'saber', 'óbice', 'ápice', 'ânsia', 'brado', 'ceder', 'ânimo', 'gleba', 'pária', 'graça', 'assaz', 'comum', 'atroz', 'orgia', 'culto', 'temor', 'sendo', 'mundo', 'censo', 'pauta', 'fugaz', 'denso', 'cozer', 'valha', 'neném', 'ainda', 'vício']


#palavras com 6 letras
palavras_6 = ['exceto', 'cínico', 'idôneo', 'âmbito', 'néscio', 'mister', 'índole', 'vereda', 'apogeu', 'inócuo', 'convém', 'sádico', 'utopia', 'ênfase', 'escopo', 'mérito', 'alusão', 'casual', 'anseio', 'pressa', 'alheio', 'hostil', 'nocivo', 'legado', 'infame', 'cético', 'gentil', 'hétero', 'exímio', 'afável', 'clichê', 'adorno', 'paixão', 'dádiva', 'adesão', 'sóbrio', 'aferir', 'êxtase', 'astuto', 'otário', 'solene', 'limiar', 'formal', 'sessão', 'safado', 'apreço', 'larica', 'julgar', 'difuso', 'hábito', 'lábaro', 'ensejo', 'ocioso', 'também', 'eficaz', 'outrem', 'júbilo', 'ímpeto', 'glória', 'alento', 'embora', 'dispor', 'facção', 'escusa', 'exílio', 'perene', 'abster', 'lúdico', 'cessão', 'alçada', 'nuance', 'ilação', 'acento', 'isento', 'objeto', 'acesso', 'etéreo', 'tácito', 'cortês', 'sanção', 'axioma', 'sisudo', 'cobiça', 'eximir', 'mazela', 'receio', 'desejo', 'remoto', 'avidez', 'vulgar', 'buscar', 'fático', 'asseio', 'cômico', 'ciente', 'adágio', 'prazer', 'alocar']


#palavras com 7 letras
palavras_7 = ['empatia', 'embuste', 'cônjuge', 'exceção', 'efêmero', 'prolixo', 'caráter', 'verbete', 'idílico', 'análogo', 'genuíno', 'sublime', 'estória', 'pêsames', 'sucinto', 'inferir', 'apático', 'família', 'audácia', 'recesso', 'acepção', 'astúcia', 'pródigo', 'redimir', 'estigma', 'estável', 'refutar', 'cinismo', 'cultura', 'virtude', 'icônico', 'exortar', 'mórbido', 'soberba', 'trivial', 'cordial', 'síntese', 'escória', 'aspecto', 'imputar', 'mitigar', 'emergir', 'luxúria', 'anátema', 'deboche', 'candura', 'almejar', 'sucesso', 'alegria', 'aurélio', 'ademais', 'excerto', 'frívolo', 'litígio', 'caralho', 'através', 'oriundo', 'contudo', 'austero', 'sensato', 'alcunha', 'orgulho', 'fomento', 'ambíguo', 'quimera', 'salutar', 'excesso', 'ambição', 'conciso', 'coragem', 'parcial', 'imersão', 'modesto', 'relação', 'erudito', 'exótico', 'isenção', 'notório', 'demanda', 'exilado', 'padecer', 'saudade', 'colosso', 'escroto', 'volátil', 'auferir', 'inércia', 'colapso', 'ansioso', 'déspota', 'difusão', 'intenso', 'amizade', 'emotivo', 'vigente', 'piedade', 'profano']



#palavras com 8 letras
palavras_8 = ['inerente', 'peculiar', 'denegrir', 'respeito', 'anuência', 'deferido', 'prudente', 'equidade', 'pandemia', 'iminente', 'invasivo', 'essência', 'misógino', 'alienado', 'eminente', 'extensão', 'abstrato', 'empírico', 'premissa', 'conceito', 'ardiloso', 'reiterar', 'ascensão', 'talarico', 'passível', 'devaneio', 'prodígio', 'lascívia', 'relativo', 'conserto', 'modéstia', 'apologia', 'analogia', 'inserção', 'ativista', 'inóspito', 'monótono', 'respaldo', 'medíocre', 'remissão', 'gratidão', 'sinônimo', 'concerne', 'alicerce', 'despeito', 'retórica', 'destarte', 'fomentar', 'rechaçar', 'proceder', 'metódico', 'notívago', 'demagogo', 'primazia', 'consiste', 'distinto', 'abnegado', 'critério', 'portanto', 'desfecho', 'elegível', 'sucumbir', 'suscitar', 'complexo', 'perfídia', 'singular', 'escárnio', 'amálgama', 'história', 'inefável', 'paradoxo', 'vocábulo', 'espectro', 'jurídico', 'processo', 'desígnio', 'instigar', 'contexto', 'verídico', 'obstante', 'maestria', 'refletir', 'solícito', 'sanidade', 'resoluto', 'impávido', 'comunhão', 'insípido', 'objetivo', 'paralelo', 'expedido', 'endêmico', 'repudiar', 'problema', 'imanente', 'emulação', 'prosaico']


#palavras com 9 letras
palavras_9 =  ['perspicaz', 'recíproco', 'impressão', 'concessão', 'supérfluo', 'escrúpulo', 'retificar','paradigma', 'presunção', 'concepção', 'dicotomia', 'implícito', 'propósito', 'hipócrita', 'plenitude', 'essencial', 'ratificar', 'hegemonia', 'corolário', 'incidente', 'esdrúxulo', 'hermético', 'persuadir', 'altruísmo', 'aleatório', 'promíscuo', 'deliberar', 'altruísta', 'esperança', 'sapiência', 'confiança', 'demasiado', 'indelével', 'mesquinho', 'resignado', 'eminência', 'regozijar', 'impetuoso', 'descrição', 'diligente', 'inusitado', 'compaixão', 'prudência', 'pretensão', 'analítico', 'discrição', 'explícito', 'exequível', 'desdenhar', 'autóctone', 'fidedigno', 'dissensão', 'ordinário', 'nostalgia', 'companhia', 'percepção', 'constante', 'resolução', 'taciturno', 'subjetivo', 'autêntico', 'supressão', 'expressão', 'imparcial', 'restrição', 'execrável', 'discorrer', 'autonomia', 'ignorante', 'adjacente', 'jactância', 'arrogante', 'obstinado', 'instância', 'interesse', 'sintético', 'cognitivo', 'iminência', 'limítrofe', 'outrossim', 'presságio', 'consoante', 'paciência', 'irascível', 'desumilde', 'eloquente', 'ludibriar', 'relevante', 'vagabunda', 'aquisição', 'estagnado', 'pederasta', 'empecilho', 'ambicioso', 'leniência', 'convicção', 'recíproca', 'plausível', 'excelente']


#palavras com 10 letras
palavras_10 = ['dicionário', 'prescindir', 'intrínseco', 'presunçoso', 'diligência', 'corroborar', 'intempérie', 'detrimento', 'maturidade', 'parcimônia', 'referência', 'inspiração', 'inexorável', 'incipiente', 'prepotente', 'pragmático', 'sororidade', 'indulgente', 'serenidade', 'arbitrário', 'disruptivo', 'auspicioso', 'sagacidade', 'iniquidade', 'pertinente', 'resignação', 'preconizar', 'precedente', 'vislumbrar', 'incidência', 'subestimar', 'disposição', 'lisonjeado', 'suscetível', 'hipocrisia', 'preliminar', 'depreender', 'entretanto', 'excêntrico', 'tribulação', 'equivocado', 'retrógrado', 'anacrônico', 'indolência', 'ingerência', 'escrutínio', 'excelência', 'infortúnio', 'fleumático', 'contemplar', 'compassivo', 'restringir', 'sintetizar', 'signatário', 'coercitivo', 'importante', 'democracia', 'pejorativo', 'primordial', 'proposição', 'finalidade', 'conjuntura', 'pecuniária', 'dissolução', 'espontâneo', 'esplêndido', 'designação', 'transeunte', 'itinerário', 'subjacente', 'alteridade', 'intrínseca', 'necessário', 'desprovido', 'sarcástico', 'pernóstico', 'divergente', 'privilégio', 'verossímil', 'exacerbado', 'pernicioso', 'pusilânime', 'relevância', 'disseminar', 'constância', 'idoneidade', 'inferência', 'militância', 'meticuloso', 'esporádico', 'satisfação', 'consolidar', 'estupefato', 'morosidade', 'disciplina', 'reverberar', 'felicidade', 'subversivo']


#palavras com 11 letras
palavras_11 = ['significado', 'perspectiva', 'resiliência', 'dissimulado', 'vicissitude', 'complacente', 'peremptório', 'contundente', 'comorbidade', 'compreensão', 'perspicácia', 'expectativa', 'beneplácito', 'subterfúgio', 'pressuposto', 'preconceito', 'indiferente', 'pretensioso', 'beligerante', 'consonância', 'imensurável', 'transcender', 'proeminente', 'intensidade', 'contingente', 'superficial', 'inenarrável', 'contencioso', 'concernente', 'experiência', 'necessidade', 'animosidade', 'benignidade', 'antagonismo', 'incumbência', 'vocabulário', 'intervenção', 'reivindicar', 'cumprimento', 'indiferença', 'supracitado', 'compreender', 'resistência', 'deliberação', 'estereótipo', 'especulação', 'proveniente', 'ambiguidade', 'subsequente', 'elucubração', 'diversidade', 'divergência', 'indubitável', 'prognóstico', 'indulgência', 'benevolente', 'integridade', 'redundância', 'heterogêneo', 'tergiversar', 'importância', 'displicente', 'oportunista', 'austeridade', 'conveniente', 'identificar', 'estabelecer', 'substantivo', 'congruência', 'negligência', 'providência', 'discriminar', 'conferência', 'admoestação', 'compulsório', 'excepcional', 'consciência', 'pragmatismo', 'verborragia', 'facultativo', 'sistemático', 'generalizar', 'subordinado', 'intelectual', 'intersecção', 'comprimento', 'contradição', 'melancólico', 'desenvolver', 'substancial', 'procedência', 'retificação', 'determinado', 'autoritário', 'consecutivo', 'conservador', 'dificuldade', 'relativizar', 'desprezível', 'enfermidade']


# Banco de palavras que será chamado pelo arquivo main, organizando todos dentro de si
palavras = [palavras_5, palavras_6, palavras_7, palavras_8, palavras_9, palavras_10, palavras_11]

# Serve para  esse bloco de codigo ser executado somente se for aberto
# Se nao usar essa verificação, quando for importado irá executar tais funções e alterar a funcionabilidade 
if __name__ == "__main__":
    def main():
    # Serve para mostrar a quantidade de palavras dentro do banco de palavras
        soma = len(palavras_5) + len(palavras_6) + len(palavras_7) + len(palavras_8) + len(palavras_9) + len(palavras_10) + len(palavras_11)
        print("O banco possui",soma, "palavras.")
        input()
    main()  